Add-Type -AssemblyName System.Drawing
$img = [System.Drawing.Image]::FromFile("c:\Users\kille\OneDrive\Documentos\Respositorio\EngineWallpaper\ui\logo-app.png")
$rect = New-Object System.Drawing.Rectangle(368, 112, 800, 800)
$bmp = new-object System.Drawing.Bitmap($rect.Width, $rect.Height)
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.DrawImage($img, (New-Object System.Drawing.Rectangle(0, 0, $bmp.Width, $bmp.Height)), $rect, [System.Drawing.GraphicsUnit]::Pixel)
$g.Dispose()
$img.Dispose()
$bmp.Save("c:\Users\kille\OneDrive\Documentos\Respositorio\EngineWallpaper\ui\logo-app-zoomed.png", [System.Drawing.Imaging.ImageFormat]::Png)
$bmp.Dispose()
